---

- name: ""
  hosts: umbrel
  gather_facts: no
  tasks:

    - block:

      - name: Modify bitcoin.conf
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/bitcoin/bitcoin.conf
            insertafter: 'rpcallowip=127.0.0.1'
            line: 'rpcallowip={{ local_network }}'
            firstmatch: yes
        notify: Restart services

      - name: Modify docker-compose.yml
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/docker-compose.yml
            insertbefore: '"\$BITCOIN_P2P_PORT:\$BITCOIN_P2P_PORT"'
            line: '                    - "$BITCOIN_RPC_PORT:$BITCOIN_RPC_PORT"'
            firstmatch: yes
        notify: Restart services

      when: local_network is defined

    - block:

      - name: Modify hass/docker-compose.yml
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/apps/home-assistant/docker-compose.yml
            insertafter: 'ipv4_address: $APP_HOME_ASSISTANT_IP'
            line: "    devices:"
            firstmatch: yes
        notify: Restart services
  
      - name: Modify hass/docker-compose.yml (2)
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/apps/home-assistant/docker-compose.yml
            insertafter: 'devices:'
            line: "      - {{ serial_line }}"
            firstmatch: yes
        notify: Restart services

      when: serial_line is defined

  handlers:

    - name: Restart services
      become: yes
      ansible.builtin.systemd:
        name: umbrel-startup
        state: restarted

...
