---

- name: ""
  hosts: umbrel
  gather_facts: no
  tasks:

    - block:

      - name: Modify bitcoin.conf
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/bitcoin/bitcoin.conf
            insertafter: 'rpcallowip=127.0.0.1'
            line: 'rpcallowip={{ bitcoin_local_network }}'
            firstmatch: yes
        notify: Reload bitcoind

      - name: Modify docker-compose.yml
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/docker-compose.yml
            insertbefore: '"\$BITCOIN_P2P_PORT:\$BITCOIN_P2P_PORT"'
            line: '                    - "$BITCOIN_RPC_PORT:$BITCOIN_RPC_PORT"'
            firstmatch: yes
        notify: Reload bitcoind

      when: bitcoin_local_network is defined

    - block:

      - name: Insert specified docker image for Home Assistant in docker-compose.yml
        ansible.builtin.replace:
            path: /home/umbrel/umbrel/apps/home-assistant/docker-compose.yml
            regexp: '^(\s*image:\s*)(.*)$'
            replace: '\1{{ hass_docker_image }}'
        notify: Reload HASS
  
      when: hass_docker_image is defined

    - block:

      - name: Modify hass/docker-compose.yml
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/apps/home-assistant/docker-compose.yml
            insertafter: 'ipv4_address: $APP_HOME_ASSISTANT_IP'
            line: "    devices:"
            firstmatch: yes
        notify: Reload HASS
  
      - name: Modify hass/docker-compose.yml (2)
        ansible.builtin.lineinfile:
            path: /home/umbrel/umbrel/apps/home-assistant/docker-compose.yml
            insertafter: 'devices:'
            line: "      - {{ hass_serial_line }}"
            firstmatch: yes
        notify: Reload HASS

      when: hass_serial_line is defined

  handlers:

    - name: Reload HASS
      ansible.builtin.shell: |
        set -euo pipefail
        ~/umbrel/scripts/app stop home-assistant
        ~/umbrel/scripts/app install home-assistant
      args:
        executable: /bin/bash

    - name: Reload bitcoind
      ansible.builtin.shell: |
        set -euo pipefail
        cd ~/umbrel
        docker-compose restart bitcoin
      args:
        executable: /bin/bash

...
